# .pages.yml Example
media:
  input: public/images
  output: /images
content:
  - name: blog
    label: Blog Posts
    path: src/content/blog
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
