media:
  input: public/images
  output: /images
content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    # Updated to include '.md' or '.mdx' explicitly if needed
    filename: "{year}-{month}-{day}-{slug}.md" 
    extension: md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: pubDate
        label: Publication Date
        type: date
        options:
          format: "yyyy-MM-dd" # Recommended for Astro compatibility
      - name: description
        label: Description
        type: text # 'text' provides a textarea, 'string' is a single line
      - name: author
        label: Author
        type: string
      - name: image
        label: Cover Image
        type: image
      - name: tags
        label: Tags
        type: list # Correct for Astro arrays
      - name: body
        label: Content
        type: rich-text # Maps to the Markdown content below frontmatter
  - name: settings
    label: Site Settings
    type: single
    path: src/content
    file: src/content/settings.json
    fields:
      - name: siteTitle
        label: Site Title
        type: string
      - name: footerText
        label: Footer Text
        type: string
